#!/usr/bin/env python3
"""Index the CSVs in data/ so schedule_builder.html can offer them as bundled sets.

Writes two files, both read by the page:

  data/manifest.json  the list a web server serves; fetched at page load
  data/bundled.js     the same list with the CSV text inlined, so the page also
                      works opened straight off disk (fetch is blocked on
                      file:// URLs, a <script src> is not)

Run it after adding or re-scraping anything in data/:

    .venv/bin/python bundle_data.py
"""

from __future__ import annotations

import csv
import json
import sys
from datetime import datetime
from pathlib import Path

DATA = Path(__file__).parent / "data"
DASH = "–"  # en dash, for number ranges


def pulled_on(rows: list[dict]) -> str:
    """The most recent scrape timestamp in the file, as a short date."""
    stamps = [r.get("retrieved_at") or "" for r in rows]
    stamps = [s for s in stamps if s]
    if not stamps:
        return ""
    try:
        when = datetime.fromisoformat(max(stamps))
    except ValueError:
        return ""
    return when.strftime("%b %-d, %Y")


def summarize(path: Path) -> dict:
    """Derive a human label from what's actually in the file."""
    with path.open(newline="", encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))

    subjects, campuses, terms, numbers = set(), set(), set(), []
    for row in rows:
        if row.get("subject"):
            subjects.add(row["subject"])
        if row.get("campus"):
            campuses.add(row["campus"])
        if row.get("term"):
            terms.add(row["term"])
        digits = "".join(c for c in (row.get("catalog_number") or "") if c.isdigit())
        if digits:
            numbers.append(int(digits))

    subject_part = "+".join(sorted(subjects)) if len(subjects) <= 3 else f"{len(subjects)} subjects"
    if numbers:
        low = min(numbers) // 100 * 100
        high = max(numbers) // 100 * 100 + 99
        level_part = f"{low:03d}{DASH}{high:03d}"
    else:
        level_part = ""

    campus_part = ", ".join(sorted(campuses)) if len(campuses) <= 3 else f"{len(campuses)} campuses"
    term_part = ", ".join(sorted(terms)) if len(terms) <= 2 else f"{len(terms)} terms"

    course_part = " ".join(p for p in (subject_part, level_part) if p) or path.stem
    label = f"{term_part} · {course_part}" if term_part else course_part

    bits = [campus_part] if campus_part else []
    bits.append(f"{len(rows)} classes")
    pulled = pulled_on(rows)
    if pulled:
        bits.append(f"pulled {pulled}")
    return {"file": path.name, "label": label, "note": " · ".join(bits), "term": term_part}


def main() -> int:
    if not DATA.is_dir():
        print(f"no {DATA} directory; nothing to index", file=sys.stderr)
        return 1

    files = sorted(p for p in DATA.glob("*.csv"))
    if not files:
        print(f"no CSVs in {DATA}", file=sys.stderr)
        return 1

    sets = sorted((summarize(path) for path in files), key=lambda s: (s["term"], s["label"]))
    (DATA / "manifest.json").write_text(json.dumps({"sets": sets}, indent=2) + "\n", encoding="utf-8")

    inlined = [dict(entry, text=(DATA / entry["file"]).read_text(encoding="utf-8")) for entry in sets]
    sidecar = ["/* Generated by bundle_data.py -- do not edit. */",
               "window.BUNDLED_CSVS = " + json.dumps(inlined) + ";"]

    # Carry the no-class days too, but only once someone has filled them in.
    calendar_path = DATA / "academic-calendar.json"
    if calendar_path.is_file():
        calendar = json.loads(calendar_path.read_text(encoding="utf-8"))
        filled = any((t or {}).get("noClassDates") for t in (calendar.get("terms") or {}).values())
        if filled:
            sidecar.append("window.ACADEMIC_CALENDAR = " + json.dumps(calendar) + ";")
            print("  including academic-calendar.json")
        else:
            print("  academic-calendar.json has no dates yet; .ics exports will not skip breaks")
    (DATA / "bundled.js").write_text("\n".join(sidecar) + "\n", encoding="utf-8")

    for entry in sets:
        print(f"  {entry['file']:34} {entry['label']}  ({entry['note']})")
    size = (DATA / "bundled.js").stat().st_size
    print(f"\nindexed {len(sets)} sets -> data/manifest.json, data/bundled.js ({size / 1024:.0f} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
